package com.tacticlogistics.model.entities;
// Generated 28/09/2015 11:33:59 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BarriosId generated by hbm2java
 */
@Embeddable
public class BarriosId implements java.io.Serializable {

	private int ciudadId;
	private int barrioId;

	public BarriosId() {
	}

	public BarriosId(int ciudadId, int barrioId) {
		this.ciudadId = ciudadId;
		this.barrioId = barrioId;
	}

	@Column(name = "Ciudad_Id", nullable = false)
	public int getCiudadId() {
		return this.ciudadId;
	}

	public void setCiudadId(int ciudadId) {
		this.ciudadId = ciudadId;
	}

	@Column(name = "Barrio_Id", nullable = false)
	public int getBarrioId() {
		return this.barrioId;
	}

	public void setBarrioId(int barrioId) {
		this.barrioId = barrioId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BarriosId))
			return false;
		BarriosId castOther = (BarriosId) other;

		return (this.getCiudadId() == castOther.getCiudadId()) && (this.getBarrioId() == castOther.getBarrioId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCiudadId();
		result = 37 * result + this.getBarrioId();
		return result;
	}

}
