package com.tacticlogistics.model.entities;
// Generated 28/09/2015 11:33:59 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Ciudades generated by hbm2java
 */
@Entity
@Table(name = "Ciudades", catalog = "dbo", uniqueConstraints = @UniqueConstraint(columnNames = { "Pais_Id", "Codigo" }) )
public class Ciudades implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer ciudadId;
	private Departamentos departamentos;
	private String codigo;
	private String nombre;
	private Short ordinal;
	private Boolean activo;
	private Date fechaActualizacion;
	private String usuarioActualizacion;
	private Set<Barrios> barrioses = new HashSet<Barrios>(0);
	private Set<OrdenesTransporte> ordenesTransportesForCiudadEntregaId = new HashSet<OrdenesTransporte>(0);
	private Set<OrdenesTransporte> ordenesTransportesForCiudadOrigenId = new HashSet<OrdenesTransporte>(0);
	private Set<Direcciones> direccioneses = new HashSet<Direcciones>(0);

	public Ciudades() {
	}

	public Ciudades(Integer ciudadId, Departamentos departamentos, String codigo, String nombre, Short ordinal,
			Boolean activo, Date fechaActualizacion, String usuarioActualizacion) {
		this.ciudadId = ciudadId;
		this.departamentos = departamentos;
		this.codigo = codigo;
		this.nombre = nombre;
		this.ordinal = ordinal;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public Ciudades(Integer ciudadId, Departamentos departamentos, String codigo, String nombre, Short ordinal,
			Boolean activo, Date fechaActualizacion, String usuarioActualizacion, Set<Barrios> barrioses,
			Set<OrdenesTransporte> ordenesTransportesForCiudadEntregaId,
			Set<OrdenesTransporte> ordenesTransportesForCiudadOrigenId, Set<Direcciones> direccioneses) {
		this.ciudadId = ciudadId;
		this.departamentos = departamentos;
		this.codigo = codigo;
		this.nombre = nombre;
		this.ordinal = ordinal;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.barrioses = barrioses;
		this.ordenesTransportesForCiudadEntregaId = ordenesTransportesForCiudadEntregaId;
		this.ordenesTransportesForCiudadOrigenId = ordenesTransportesForCiudadOrigenId;
		this.direccioneses = direccioneses;
	}

	@Id

	@Column(name = "Ciudad_Id", unique = true, nullable = false)
	public Integer getCiudadId() {
		return this.ciudadId;
	}

	public void setCiudadId(Integer ciudadId) {
		this.ciudadId = ciudadId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "Pais_Id", referencedColumnName = "Pais_Id", nullable = false),
			@JoinColumn(name = "Departamento_Id", referencedColumnName = "Departamento_Id", nullable = false) })
	public Departamentos getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Departamentos departamentos) {
		this.departamentos = departamentos;
	}

	@Column(name = "Codigo", nullable = false, length = 10)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "Nombre", nullable = false, length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Ordinal", nullable = false)
	public Short getOrdinal() {
		return this.ordinal;
	}

	public void setOrdinal(Short ordinal) {
		this.ordinal = ordinal;
	}

	@Column(name = "Activo", nullable = false)
	public Boolean isActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciudades")
	public Set<Barrios> getBarrioses() {
		return this.barrioses;
	}

	public void setBarrioses(Set<Barrios> barrioses) {
		this.barrioses = barrioses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciudadesByCiudadEntregaId")
	public Set<OrdenesTransporte> getOrdenesTransportesForCiudadEntregaId() {
		return this.ordenesTransportesForCiudadEntregaId;
	}

	public void setOrdenesTransportesForCiudadEntregaId(Set<OrdenesTransporte> ordenesTransportesForCiudadEntregaId) {
		this.ordenesTransportesForCiudadEntregaId = ordenesTransportesForCiudadEntregaId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciudadesByCiudadOrigenId")
	public Set<OrdenesTransporte> getOrdenesTransportesForCiudadOrigenId() {
		return this.ordenesTransportesForCiudadOrigenId;
	}

	public void setOrdenesTransportesForCiudadOrigenId(Set<OrdenesTransporte> ordenesTransportesForCiudadOrigenId) {
		this.ordenesTransportesForCiudadOrigenId = ordenesTransportesForCiudadOrigenId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciudades")
	public Set<Direcciones> getDireccioneses() {
		return this.direccioneses;
	}

	public void setDireccioneses(Set<Direcciones> direccioneses) {
		this.direccioneses = direccioneses;
	}

}
