package com.tacticlogistics.model.entities;
// Generated 28/09/2015 11:33:59 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClientesFinalesDireccion generated by hbm2java
 */
@Entity
@Table(name = "Clientes_Finales_Direccion", catalog = "dbo")
public class ClientesFinalesDireccion implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private ClientesFinalesDireccionId id;
	private ClientesFinales clientesFinales;
	private Direcciones direcciones;
	private boolean activo;
	private Date fechaActualizacion;
	private String usuarioActualizacion;
	private Set<OrdenesTransporte> ordenesTransportes = new HashSet<OrdenesTransporte>(0);

	public ClientesFinalesDireccion() {
	}

	public ClientesFinalesDireccion(ClientesFinalesDireccionId id, ClientesFinales clientesFinales,
			Direcciones direcciones, boolean activo, Date fechaActualizacion, String usuarioActualizacion) {
		this.id = id;
		this.clientesFinales = clientesFinales;
		this.direcciones = direcciones;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public ClientesFinalesDireccion(ClientesFinalesDireccionId id, ClientesFinales clientesFinales,
			Direcciones direcciones, boolean activo, Date fechaActualizacion, String usuarioActualizacion,
			Set<OrdenesTransporte> ordenesTransportes) {
		this.id = id;
		this.clientesFinales = clientesFinales;
		this.direcciones = direcciones;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ordenesTransportes = ordenesTransportes;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "clienteFinalId", column = @Column(name = "Cliente_Final_Id", nullable = false) ),
			@AttributeOverride(name = "direccionId", column = @Column(name = "Direccion_Id", nullable = false) ) })
	public ClientesFinalesDireccionId getId() {
		return this.id;
	}

	public void setId(ClientesFinalesDireccionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Cliente_Final_Id", nullable = false, insertable = false, updatable = false)
	public ClientesFinales getClientesFinales() {
		return this.clientesFinales;
	}

	public void setClientesFinales(ClientesFinales clientesFinales) {
		this.clientesFinales = clientesFinales;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Direccion_Id", nullable = false, insertable = false, updatable = false)
	public Direcciones getDirecciones() {
		return this.direcciones;
	}

	public void setDirecciones(Direcciones direcciones) {
		this.direcciones = direcciones;
	}

	@Column(name = "Activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientesFinalesDireccion")
	public Set<OrdenesTransporte> getOrdenesTransportes() {
		return this.ordenesTransportes;
	}

	public void setOrdenesTransportes(Set<OrdenesTransporte> ordenesTransportes) {
		this.ordenesTransportes = ordenesTransportes;
	}

}
