package com.tacticlogistics.model.entities;
// Generated 28/09/2015 11:33:59 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ClientesFinales generated by hbm2java
 */
@Entity
@Table(name = "Clientes_Finales", catalog = "dbo", uniqueConstraints = @UniqueConstraint(columnNames = { "Cliente_Id",
		"Identificacion" }) )
public class ClientesFinales implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int clienteFinalId;
	private Clientes clientes;
	private TiposIdentificacion tiposIdentificacion;
	private String identificacion;
	private String nombre;
	private boolean activo;
	private Date fechaActualizacion;
	private String usuarioActualizacion;
	private Set<ClientesFinalesDireccion> clientesFinalesDireccions = new HashSet<ClientesFinalesDireccion>(0);

	public ClientesFinales() {
	}

	public ClientesFinales(int clienteFinalId, Clientes clientes, TiposIdentificacion tiposIdentificacion,
			String identificacion, String nombre, boolean activo, Date fechaActualizacion,
			String usuarioActualizacion) {
		this.clienteFinalId = clienteFinalId;
		this.clientes = clientes;
		this.tiposIdentificacion = tiposIdentificacion;
		this.identificacion = identificacion;
		this.nombre = nombre;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public ClientesFinales(int clienteFinalId, Clientes clientes, TiposIdentificacion tiposIdentificacion,
			String identificacion, String nombre, boolean activo, Date fechaActualizacion, String usuarioActualizacion,
			Set<ClientesFinalesDireccion> clientesFinalesDireccions) {
		this.clienteFinalId = clienteFinalId;
		this.clientes = clientes;
		this.tiposIdentificacion = tiposIdentificacion;
		this.identificacion = identificacion;
		this.nombre = nombre;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.clientesFinalesDireccions = clientesFinalesDireccions;
	}

	@Id

	@Column(name = "Cliente_Final_Id", unique = true, nullable = false)
	public int getClienteFinalId() {
		return this.clienteFinalId;
	}

	public void setClienteFinalId(int clienteFinalId) {
		this.clienteFinalId = clienteFinalId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Cliente_Id", nullable = false)
	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Tipo_Identificacion_Id", nullable = false)
	public TiposIdentificacion getTiposIdentificacion() {
		return this.tiposIdentificacion;
	}

	public void setTiposIdentificacion(TiposIdentificacion tiposIdentificacion) {
		this.tiposIdentificacion = tiposIdentificacion;
	}

	@Column(name = "Identificacion", nullable = false, length = 20)
	public String getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(String identificacion) {
		this.identificacion = identificacion;
	}

	@Column(name = "Nombre", nullable = false, length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientesFinales")
	public Set<ClientesFinalesDireccion> getClientesFinalesDireccions() {
		return this.clientesFinalesDireccions;
	}

	public void setClientesFinalesDireccions(Set<ClientesFinalesDireccion> clientesFinalesDireccions) {
		this.clientesFinalesDireccions = clientesFinalesDireccions;
	}

}
