package com.tacticlogistics.model.entities;
// Generated 28/09/2015 11:33:59 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name = "Clientes", catalog = "dbo")
public class Clientes implements java.io.Serializable {

	private int clienteId;
	private TiposIdentificacion tiposIdentificacion;
	private String identificacion;
	private String razonSocial;
	private String nombreComercial;
	private boolean activo;
	private Date fechaActualizacion;
	private String usuarioActualizacion;
	private Set<ClientesFinales> clientesFinaleses = new HashSet<ClientesFinales>(0);
	private Set<RadicacionesOrdenTransporte> radicacionesOrdenTransportes = new HashSet<RadicacionesOrdenTransporte>(0);

	public Clientes() {
	}

	public Clientes(int clienteId, TiposIdentificacion tiposIdentificacion, String identificacion, String razonSocial,
			String nombreComercial, boolean activo, Date fechaActualizacion, String usuarioActualizacion) {
		this.clienteId = clienteId;
		this.tiposIdentificacion = tiposIdentificacion;
		this.identificacion = identificacion;
		this.razonSocial = razonSocial;
		this.nombreComercial = nombreComercial;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public Clientes(int clienteId, TiposIdentificacion tiposIdentificacion, String identificacion, String razonSocial,
			String nombreComercial, boolean activo, Date fechaActualizacion, String usuarioActualizacion,
			Set<ClientesFinales> clientesFinaleses, Set<RadicacionesOrdenTransporte> radicacionesOrdenTransportes) {
		this.clienteId = clienteId;
		this.tiposIdentificacion = tiposIdentificacion;
		this.identificacion = identificacion;
		this.razonSocial = razonSocial;
		this.nombreComercial = nombreComercial;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.clientesFinaleses = clientesFinaleses;
		this.radicacionesOrdenTransportes = radicacionesOrdenTransportes;
	}

	@Id

	@Column(name = "Cliente_Id", unique = true, nullable = false)
	public int getClienteId() {
		return this.clienteId;
	}

	public void setClienteId(int clienteId) {
		this.clienteId = clienteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Tipo_Identificacion_Id", nullable = false)
	public TiposIdentificacion getTiposIdentificacion() {
		return this.tiposIdentificacion;
	}

	public void setTiposIdentificacion(TiposIdentificacion tiposIdentificacion) {
		this.tiposIdentificacion = tiposIdentificacion;
	}

	@Column(name = "Identificacion", nullable = false, length = 20)
	public String getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(String identificacion) {
		this.identificacion = identificacion;
	}

	@Column(name = "Razon_Social", nullable = false, length = 200)
	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	@Column(name = "Nombre_Comercial", nullable = false, length = 200)
	public String getNombreComercial() {
		return this.nombreComercial;
	}

	public void setNombreComercial(String nombreComercial) {
		this.nombreComercial = nombreComercial;
	}

	@Column(name = "Activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientes")
	public Set<ClientesFinales> getClientesFinaleses() {
		return this.clientesFinaleses;
	}

	public void setClientesFinaleses(Set<ClientesFinales> clientesFinaleses) {
		this.clientesFinaleses = clientesFinaleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientes")
	public Set<RadicacionesOrdenTransporte> getRadicacionesOrdenTransportes() {
		return this.radicacionesOrdenTransportes;
	}

	public void setRadicacionesOrdenTransportes(Set<RadicacionesOrdenTransporte> radicacionesOrdenTransportes) {
		this.radicacionesOrdenTransportes = radicacionesOrdenTransportes;
	}

}
