package com.tacticlogistics.model.entities;
// Generated 28/09/2015 11:33:59 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClientesCodigoAlternoId generated by hbm2java
 */
@Embeddable
public class ClientesCodigoAlternoId implements java.io.Serializable {

	private int clienteId;
	private String aplicacionId;

	public ClientesCodigoAlternoId() {
	}

	public ClientesCodigoAlternoId(int clienteId, String aplicacionId) {
		this.clienteId = clienteId;
		this.aplicacionId = aplicacionId;
	}

	@Column(name = "Cliente_Id", nullable = false)
	public int getClienteId() {
		return this.clienteId;
	}

	public void setClienteId(int clienteId) {
		this.clienteId = clienteId;
	}

	@Column(name = "Aplicacion_Id", nullable = false, length = 20)
	public String getAplicacionId() {
		return this.aplicacionId;
	}

	public void setAplicacionId(String aplicacionId) {
		this.aplicacionId = aplicacionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClientesCodigoAlternoId))
			return false;
		ClientesCodigoAlternoId castOther = (ClientesCodigoAlternoId) other;

		return (this.getClienteId() == castOther.getClienteId())
				&& ((this.getAplicacionId() == castOther.getAplicacionId())
						|| (this.getAplicacionId() != null && castOther.getAplicacionId() != null
								&& this.getAplicacionId().equals(castOther.getAplicacionId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClienteId();
		result = 37 * result + (getAplicacionId() == null ? 0 : this.getAplicacionId().hashCode());
		return result;
	}

}
