package com.tacticlogistics.model.entities;
// Generated 28/09/2015 11:33:59 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClientesCodigoAlterno generated by hbm2java
 */
@Entity
@Table(name = "Clientes_Codigo_Alterno", catalog = "dbo")
public class ClientesCodigoAlterno implements java.io.Serializable {

	private ClientesCodigoAlternoId id;
	private String codigo;
	private boolean activo;
	private Date fechaActualizacion;
	private String usuarioActualizacion;

	public ClientesCodigoAlterno() {
	}

	public ClientesCodigoAlterno(ClientesCodigoAlternoId id, String codigo, boolean activo, Date fechaActualizacion,
			String usuarioActualizacion) {
		this.id = id;
		this.codigo = codigo;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "clienteId", column = @Column(name = "Cliente_Id", nullable = false) ),
			@AttributeOverride(name = "aplicacionId", column = @Column(name = "Aplicacion_Id", nullable = false, length = 20) ) })
	public ClientesCodigoAlternoId getId() {
		return this.id;
	}

	public void setId(ClientesCodigoAlternoId id) {
		this.id = id;
	}

	@Column(name = "Codigo", nullable = false, length = 50)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "Activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 27)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

}
