package com.tacticlogistics.model.entities;
// Generated 28/09/2015 11:33:59 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DepartamentosId generated by hbm2java
 */
@Embeddable
public class DepartamentosId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Short paisId;
	private Short departamentoId;

	public DepartamentosId() {
	}

	public DepartamentosId(Short paisId, Short departamentoId) {
		this.paisId = paisId;
		this.departamentoId = departamentoId;
	}

	@Column(name = "Pais_Id", nullable = false)
	public Short getPaisId() {
		return this.paisId;
	}

	public void setPaisId(Short paisId) {
		this.paisId = paisId;
	}

	@Column(name = "Departamento_Id", nullable = false)
	public Short getDepartamentoId() {
		return this.departamentoId;
	}

	public void setDepartamentoId(Short departamentoId) {
		this.departamentoId = departamentoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DepartamentosId))
			return false;
		DepartamentosId castOther = (DepartamentosId) other;

		return (this.getPaisId() == castOther.getPaisId())
				&& (this.getDepartamentoId() == castOther.getDepartamentoId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPaisId();
		result = 37 * result + this.getDepartamentoId();
		return result;
	}

}
