package com.tacticlogistics.model.entities;
// Generated 28/09/2015 11:33:59 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EstadosOrdenTransporte generated by hbm2java
 */
@Entity
@Table(name = "Estados_Orden_Transporte", catalog = "dbo")
public class EstadosOrdenTransporte implements java.io.Serializable {

	private byte estadoOrdenTransporteId;
	private String codigo;
	private String nombre;
	private short ordinal;
	private boolean activo;
	private Date fechaActualizacion;
	private String usuarioActualizacion;
	private Set<OrdenesTransporte> ordenesTransportes = new HashSet<OrdenesTransporte>(0);

	public EstadosOrdenTransporte() {
	}

	public EstadosOrdenTransporte(byte estadoOrdenTransporteId, String codigo, String nombre, short ordinal,
			boolean activo, Date fechaActualizacion, String usuarioActualizacion) {
		this.estadoOrdenTransporteId = estadoOrdenTransporteId;
		this.codigo = codigo;
		this.nombre = nombre;
		this.ordinal = ordinal;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public EstadosOrdenTransporte(byte estadoOrdenTransporteId, String codigo, String nombre, short ordinal,
			boolean activo, Date fechaActualizacion, String usuarioActualizacion,
			Set<OrdenesTransporte> ordenesTransportes) {
		this.estadoOrdenTransporteId = estadoOrdenTransporteId;
		this.codigo = codigo;
		this.nombre = nombre;
		this.ordinal = ordinal;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.ordenesTransportes = ordenesTransportes;
	}

	@Id

	@Column(name = "Estado_Orden_Transporte_Id", unique = true, nullable = false)
	public byte getEstadoOrdenTransporteId() {
		return this.estadoOrdenTransporteId;
	}

	public void setEstadoOrdenTransporteId(byte estadoOrdenTransporteId) {
		this.estadoOrdenTransporteId = estadoOrdenTransporteId;
	}

	@Column(name = "Codigo", nullable = false, length = 2)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "Nombre", nullable = false, length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Ordinal", nullable = false)
	public short getOrdinal() {
		return this.ordinal;
	}

	public void setOrdinal(short ordinal) {
		this.ordinal = ordinal;
	}

	@Column(name = "Activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadosOrdenTransporte")
	public Set<OrdenesTransporte> getOrdenesTransportes() {
		return this.ordenesTransportes;
	}

	public void setOrdenesTransportes(Set<OrdenesTransporte> ordenesTransportes) {
		this.ordenesTransportes = ordenesTransportes;
	}

}
