package com.tacticlogistics.model.entities;
// Generated 28/09/2015 11:33:59 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OperadoresCentroDistribucion generated by hbm2java
 */
@Entity
@Table(name = "Operadores_Centro_Distribucion", catalog = "dbo")
public class OperadoresCentroDistribucion implements java.io.Serializable {

	private short operadorCentroDistribucionId;
	private String tipoIdentificacionId;
	private String identificacion;
	private String nombre;
	private int direccionId;
	private byte tipoOperadorCentroDistribucionId;
	private boolean activo;
	private Date fechaActualizacion;
	private String usuarioActualizacion;
	private Set<CentrosDistribucion> centrosDistribucions = new HashSet<CentrosDistribucion>(0);

	public OperadoresCentroDistribucion() {
	}

	public OperadoresCentroDistribucion(short operadorCentroDistribucionId, String tipoIdentificacionId,
			String identificacion, String nombre, int direccionId, byte tipoOperadorCentroDistribucionId,
			boolean activo, Date fechaActualizacion, String usuarioActualizacion) {
		this.operadorCentroDistribucionId = operadorCentroDistribucionId;
		this.tipoIdentificacionId = tipoIdentificacionId;
		this.identificacion = identificacion;
		this.nombre = nombre;
		this.direccionId = direccionId;
		this.tipoOperadorCentroDistribucionId = tipoOperadorCentroDistribucionId;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public OperadoresCentroDistribucion(short operadorCentroDistribucionId, String tipoIdentificacionId,
			String identificacion, String nombre, int direccionId, byte tipoOperadorCentroDistribucionId,
			boolean activo, Date fechaActualizacion, String usuarioActualizacion,
			Set<CentrosDistribucion> centrosDistribucions) {
		this.operadorCentroDistribucionId = operadorCentroDistribucionId;
		this.tipoIdentificacionId = tipoIdentificacionId;
		this.identificacion = identificacion;
		this.nombre = nombre;
		this.direccionId = direccionId;
		this.tipoOperadorCentroDistribucionId = tipoOperadorCentroDistribucionId;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.centrosDistribucions = centrosDistribucions;
	}

	@Id

	@Column(name = "Operador_Centro_Distribucion_Id", unique = true, nullable = false)
	public short getOperadorCentroDistribucionId() {
		return this.operadorCentroDistribucionId;
	}

	public void setOperadorCentroDistribucionId(short operadorCentroDistribucionId) {
		this.operadorCentroDistribucionId = operadorCentroDistribucionId;
	}

	@Column(name = "Tipo_Identificacion_Id", nullable = false, length = 2)
	public String getTipoIdentificacionId() {
		return this.tipoIdentificacionId;
	}

	public void setTipoIdentificacionId(String tipoIdentificacionId) {
		this.tipoIdentificacionId = tipoIdentificacionId;
	}

	@Column(name = "Identificacion", nullable = false, length = 20)
	public String getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(String identificacion) {
		this.identificacion = identificacion;
	}

	@Column(name = "Nombre", nullable = false, length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Direccion_Id", nullable = false)
	public int getDireccionId() {
		return this.direccionId;
	}

	public void setDireccionId(int direccionId) {
		this.direccionId = direccionId;
	}

	@Column(name = "Tipo_Operador_Centro_Distribucion_Id", nullable = false)
	public byte getTipoOperadorCentroDistribucionId() {
		return this.tipoOperadorCentroDistribucionId;
	}

	public void setTipoOperadorCentroDistribucionId(byte tipoOperadorCentroDistribucionId) {
		this.tipoOperadorCentroDistribucionId = tipoOperadorCentroDistribucionId;
	}

	@Column(name = "Activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operadoresCentroDistribucion")
	public Set<CentrosDistribucion> getCentrosDistribucions() {
		return this.centrosDistribucions;
	}

	public void setCentrosDistribucions(Set<CentrosDistribucion> centrosDistribucions) {
		this.centrosDistribucions = centrosDistribucions;
	}

}
