package com.tacticlogistics.model.entities;
// Generated 28/09/2015 11:33:59 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrdenesTransporteObservacion generated by hbm2java
 */
@Entity
@Table(name = "Ordenes_Transporte_Observacion", catalog = "dbo")
public class OrdenesTransporteObservacion implements java.io.Serializable {

	private OrdenesTransporteObservacionId id;
	private String observacion;
	private Date fechaActualizacion;
	private String usuarioActualizacion;

	public OrdenesTransporteObservacion() {
	}

	public OrdenesTransporteObservacion(OrdenesTransporteObservacionId id, String observacion, Date fechaActualizacion,
			String usuarioActualizacion) {
		this.id = id;
		this.observacion = observacion;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ordenTransporteId", column = @Column(name = "Orden_Transporte_Id", nullable = false) ),
			@AttributeOverride(name = "tipoObservacionOrdenTransporteId", column = @Column(name = "Tipo_Observacion_Orden_Transporte_Id", nullable = false) ) })
	public OrdenesTransporteObservacionId getId() {
		return this.id;
	}

	public void setId(OrdenesTransporteObservacionId id) {
		this.id = id;
	}

	@Column(name = "Observacion", nullable = false, length = 500)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

}
