package com.tacticlogistics.model.entities;
// Generated 28/09/2015 11:33:59 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * OrdenesTransporteVehiculo generated by hbm2java
 */
@Entity
@Table(name = "Ordenes_Transporte_Vehiculo", catalog = "dbo")
public class OrdenesTransporteVehiculo implements java.io.Serializable {

	private int ordenTransporteId;
	private OrdenesTransporte ordenesTransporte;
	private byte tipoVehiculoId;
	private String numeroPlaca;
	private String tipoIdentificacionId;
	private String identificacion;
	private String nombreConductor;
	private Date fechaActualizacion;
	private String usuarioActualizacion;

	public OrdenesTransporteVehiculo() {
	}

	public OrdenesTransporteVehiculo(OrdenesTransporte ordenesTransporte, byte tipoVehiculoId, String numeroPlaca,
			String tipoIdentificacionId, String identificacion, String nombreConductor, Date fechaActualizacion,
			String usuarioActualizacion) {
		this.ordenesTransporte = ordenesTransporte;
		this.tipoVehiculoId = tipoVehiculoId;
		this.numeroPlaca = numeroPlaca;
		this.tipoIdentificacionId = tipoIdentificacionId;
		this.identificacion = identificacion;
		this.nombreConductor = nombreConductor;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "ordenesTransporte") )
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "Orden_Transporte_Id", unique = true, nullable = false)
	public int getOrdenTransporteId() {
		return this.ordenTransporteId;
	}

	public void setOrdenTransporteId(int ordenTransporteId) {
		this.ordenTransporteId = ordenTransporteId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public OrdenesTransporte getOrdenesTransporte() {
		return this.ordenesTransporte;
	}

	public void setOrdenesTransporte(OrdenesTransporte ordenesTransporte) {
		this.ordenesTransporte = ordenesTransporte;
	}

	@Column(name = "Tipo_Vehiculo_Id", nullable = false)
	public byte getTipoVehiculoId() {
		return this.tipoVehiculoId;
	}

	public void setTipoVehiculoId(byte tipoVehiculoId) {
		this.tipoVehiculoId = tipoVehiculoId;
	}

	@Column(name = "Numero_Placa", nullable = false, length = 10)
	public String getNumeroPlaca() {
		return this.numeroPlaca;
	}

	public void setNumeroPlaca(String numeroPlaca) {
		this.numeroPlaca = numeroPlaca;
	}

	@Column(name = "Tipo_Identificacion_Id", nullable = false, length = 2)
	public String getTipoIdentificacionId() {
		return this.tipoIdentificacionId;
	}

	public void setTipoIdentificacionId(String tipoIdentificacionId) {
		this.tipoIdentificacionId = tipoIdentificacionId;
	}

	@Column(name = "Identificacion", nullable = false, length = 20)
	public String getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(String identificacion) {
		this.identificacion = identificacion;
	}

	@Column(name = "Nombre_Conductor", nullable = false, length = 200)
	public String getNombreConductor() {
		return this.nombreConductor;
	}

	public void setNombreConductor(String nombreConductor) {
		this.nombreConductor = nombreConductor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

}
