package com.tacticlogistics.model.entities;
// Generated 28/09/2015 11:33:59 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TiposObservacionOrdenTransporte generated by hbm2java
 */
@Entity
@Table(name = "Tipos_Observacion_Orden_Transporte", catalog = "dbo")
public class TiposObservacionOrdenTransporte implements java.io.Serializable {

	private short tipoObservacionOrdenTransporteId;
	private String codigo;
	private String nombre;
	private String descripcion;
	private byte obligatoriedad;
	private short ordinal;
	private boolean activo;
	private Date fechaActualizacion;
	private String usuarioActualizacion;

	public TiposObservacionOrdenTransporte() {
	}

	public TiposObservacionOrdenTransporte(short tipoObservacionOrdenTransporteId, String codigo, String nombre,
			String descripcion, byte obligatoriedad, short ordinal, boolean activo, Date fechaActualizacion,
			String usuarioActualizacion) {
		this.tipoObservacionOrdenTransporteId = tipoObservacionOrdenTransporteId;
		this.codigo = codigo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.obligatoriedad = obligatoriedad;
		this.ordinal = ordinal;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@Id

	@Column(name = "Tipo_Observacion_Orden_Transporte_Id", unique = true, nullable = false)
	public short getTipoObservacionOrdenTransporteId() {
		return this.tipoObservacionOrdenTransporteId;
	}

	public void setTipoObservacionOrdenTransporteId(short tipoObservacionOrdenTransporteId) {
		this.tipoObservacionOrdenTransporteId = tipoObservacionOrdenTransporteId;
	}

	@Column(name = "Codigo", nullable = false, length = 20)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "Nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Descripcion", nullable = false, length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "Obligatoriedad", nullable = false)
	public byte getObligatoriedad() {
		return this.obligatoriedad;
	}

	public void setObligatoriedad(byte obligatoriedad) {
		this.obligatoriedad = obligatoriedad;
	}

	@Column(name = "Ordinal", nullable = false)
	public short getOrdinal() {
		return this.ordinal;
	}

	public void setOrdinal(short ordinal) {
		this.ordinal = ordinal;
	}

	@Column(name = "Activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

}
