package com.tacticlogistics.model.entities;
// Generated 28/09/2015 11:33:59 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TiposDireccion generated by hbm2java
 */
@Entity
@Table(name = "Tipos_Direccion", catalog = "dbo")
public class TiposDireccion implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer tipoDireccionId;
	private String codigo;
	private String nombre;
	private String descripcion;
	private Boolean principal;
	private Short ordinal;
	private Boolean activo;
	private Date fechaActualizacion;
	private String usuarioActualizacion;
	private Set<Direcciones> direccioneses = new HashSet<Direcciones>(0);

	public TiposDireccion() {
	}

	public TiposDireccion(Integer tipoDireccionId, String codigo, String nombre, String descripcion, Boolean principal,
			Short ordinal, Boolean activo, Date fechaActualizacion, String usuarioActualizacion) {
		this.tipoDireccionId = tipoDireccionId;
		this.codigo = codigo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.principal = principal;
		this.ordinal = ordinal;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public TiposDireccion(Integer tipoDireccionId, String codigo, String nombre, String descripcion, Boolean principal,
			Short ordinal, Boolean activo, Date fechaActualizacion, String usuarioActualizacion,
			Set<Direcciones> direccioneses) {
		this.tipoDireccionId = tipoDireccionId;
		this.codigo = codigo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.principal = principal;
		this.ordinal = ordinal;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.direccioneses = direccioneses;
	}

	@Id
	@Column(name = "Tipo_Direccion_Id", unique = true, nullable = false)
	public Integer getTipoDireccionId() {
		return this.tipoDireccionId;
	}

	public void setTipoDireccionId(Integer tipoDireccionId) {
		this.tipoDireccionId = tipoDireccionId;
	}

	@Column(name = "Codigo", nullable = false, length = 20)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "Nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Descripcion", nullable = false, length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "Principal", nullable = false)
	public Boolean isPrincipal() {
		return this.principal;
	}

	public void setPrincipal(Boolean principal) {
		this.principal = principal;
	}

	@Column(name = "Ordinal", nullable = false)
	public Short getOrdinal() {
		return this.ordinal;
	}

	public void setOrdinal(Short ordinal) {
		this.ordinal = ordinal;
	}

	@Column(name = "Activo", nullable = false)
	public Boolean isActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tiposDireccion")
	public Set<Direcciones> getDireccioneses() {
		return this.direccioneses;
	}

	public void setDireccioneses(Set<Direcciones> direccioneses) {
		this.direccioneses = direccioneses;
	}

}
