package com.tacticlogistics.model.entities;
// Generated 28/09/2015 11:33:59 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TiposUsoDireccion generated by hbm2java
 */
@Entity
@Table(name = "Tipos_Uso_Direccion", catalog = "dbo")
public class TiposUsoDireccion implements java.io.Serializable {

	private byte tipoUsoDireccionId;
	private String codigo;
	private String nombre;
	private String descripcion;
	private boolean activo;
	private Date fechaActualizacion;
	private String usuarioActualizacion;

	public TiposUsoDireccion() {
	}

	public TiposUsoDireccion(byte tipoUsoDireccionId, String codigo, String nombre, String descripcion, boolean activo,
			Date fechaActualizacion, String usuarioActualizacion) {
		this.tipoUsoDireccionId = tipoUsoDireccionId;
		this.codigo = codigo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@Id

	@Column(name = "Tipo_Uso_Direccion_Id", unique = true, nullable = false)
	public byte getTipoUsoDireccionId() {
		return this.tipoUsoDireccionId;
	}

	public void setTipoUsoDireccionId(byte tipoUsoDireccionId) {
		this.tipoUsoDireccionId = tipoUsoDireccionId;
	}

	@Column(name = "Codigo", nullable = false, length = 20)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "Nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Descripcion", nullable = false, length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "Activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

}
