package com.tacticlogistics.model.entities;
// Generated 28/09/2015 11:33:59 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Zonas generated by hbm2java
 */
@Entity
@Table(name = "Zonas", catalog = "dbo")
public class Zonas implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer zonaId;
	private String codigo;
	private String nombre;
	private Short ordinal;
	private Boolean activo;
	private Date fechaActualizacion;
	private String usuarioActualizacion;
	private Set<Barrios> barrioses = new HashSet<Barrios>(0);
	private Set<Direcciones> direccioneses = new HashSet<Direcciones>(0);
	private Set<OrdenesTransporte> ordenesTransportes = new HashSet<OrdenesTransporte>(0);

	public Zonas() {
	}

	public Zonas(Integer zonaId, String codigo, String nombre, Short ordinal, Boolean activo, Date fechaActualizacion,
			String usuarioActualizacion) {
		this.zonaId = zonaId;
		this.codigo = codigo;
		this.nombre = nombre;
		this.ordinal = ordinal;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public Zonas(Integer zonaId, String codigo, String nombre, Short ordinal, Boolean activo, Date fechaActualizacion,
			String usuarioActualizacion, Set<Barrios> barrioses, Set<Direcciones> direccioneses,
			Set<OrdenesTransporte> ordenesTransportes) {
		this.zonaId = zonaId;
		this.codigo = codigo;
		this.nombre = nombre;
		this.ordinal = ordinal;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.barrioses = barrioses;
		this.direccioneses = direccioneses;
		this.ordenesTransportes = ordenesTransportes;
	}

	@Id

	@Column(name = "Zona_Id", unique = true, nullable = false)
	public Integer getZonaId() {
		return this.zonaId;
	}

	public void setZonaId(Integer zonaId) {
		this.zonaId = zonaId;
	}

	@Column(name = "Codigo", nullable = false, length = 2)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "Nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Ordinal", nullable = false)
	public Short getOrdinal() {
		return this.ordinal;
	}

	public void setOrdinal(Short ordinal) {
		this.ordinal = ordinal;
	}

	@Column(name = "Activo", nullable = false)
	public Boolean isActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "zonas")
	public Set<Barrios> getBarrioses() {
		return this.barrioses;
	}

	public void setBarrioses(Set<Barrios> barrioses) {
		this.barrioses = barrioses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "zonas")
	public Set<Direcciones> getDireccioneses() {
		return this.direccioneses;
	}

	public void setDireccioneses(Set<Direcciones> direccioneses) {
		this.direccioneses = direccioneses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "zonas")
	public Set<OrdenesTransporte> getOrdenesTransportes() {
		return this.ordenesTransportes;
	}

	public void setOrdenesTransportes(Set<OrdenesTransporte> ordenesTransportes) {
		this.ordenesTransportes = ordenesTransportes;
	}

}
