package com.tacticlogistics.model.entities;
// Generated 23-ago-2015 19:13:34 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LineasOrdenEntradaId generated by hbm2java
 */
@Embeddable
public class LineasOrdenEntradaId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer idOrdenEntrada;
	private Integer numeroLinea;

	public LineasOrdenEntradaId() {
	}

	public LineasOrdenEntradaId(Integer idOrdenEntrada, Integer numeroLinea) {
		this.idOrdenEntrada = idOrdenEntrada;
		this.numeroLinea = numeroLinea;
	}

	@Column(name = "Id_Orden_Entrada", nullable = false)
	public Integer getIdOrdenEntrada() {
		return this.idOrdenEntrada;
	}

	public void setIdOrdenEntrada(Integer idOrdenEntrada) {
		this.idOrdenEntrada = idOrdenEntrada;
	}

	@Column(name = "Numero_Linea", nullable = false)
	public Integer getNumeroLinea() {
		return this.numeroLinea;
	}

	public void setNumeroLinea(Integer numeroLinea) {
		this.numeroLinea = numeroLinea;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LineasOrdenEntradaId))
			return false;
		LineasOrdenEntradaId castOther = (LineasOrdenEntradaId) other;

		return (this.getIdOrdenEntrada() == castOther.getIdOrdenEntrada())
				&& (this.getNumeroLinea() == castOther.getNumeroLinea());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdOrdenEntrada();
		result = 37 * result + this.getNumeroLinea();
		return result;
	}

}
