package com.tacticlogistics.model.entities;
// Generated 23-ago-2015 19:13:34 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LineasOrdenEntrada generated by hbm2java
 */
@Entity
@Table(name = "Lineas_Orden_Entrada", schema = "demo", catalog = "esbTactic")
public class LineasOrdenEntrada implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private LineasOrdenEntradaId id;
	private OrdenesEntrada ordenesEntrada;
	private String idProducto;
	private String numeroLote;
	private Integer cantidad;
	private String idUnidadMedida;
	private Integer cantidadEstandar;
	private String idUnidadMedidaEstandar;
	private String idEstadoInventario;
	private Date fechaModificacion;
	private String usuarioModificacion;

	public LineasOrdenEntrada() {
	}

	public LineasOrdenEntrada(LineasOrdenEntradaId id, OrdenesEntrada ordenesEntrada, String idProducto,
			Integer cantidad, String idUnidadMedida, Integer cantidadEstandar, String idUnidadMedidaEstandar,
			String idEstadoInventario, Date fechaModificacion, String usuarioModificacion) {
		this.id = id;
		this.ordenesEntrada = ordenesEntrada;
		this.idProducto = idProducto;
		this.cantidad = cantidad;
		this.idUnidadMedida = idUnidadMedida;
		this.cantidadEstandar = cantidadEstandar;
		this.idUnidadMedidaEstandar = idUnidadMedidaEstandar;
		this.idEstadoInventario = idEstadoInventario;
		this.fechaModificacion = fechaModificacion;
		this.usuarioModificacion = usuarioModificacion;
	}

	public LineasOrdenEntrada(LineasOrdenEntradaId id, OrdenesEntrada ordenesEntrada, String idProducto,
			String numeroLote, Integer cantidad, String idUnidadMedida, Integer cantidadEstandar,
			String idUnidadMedidaEstandar, String idEstadoInventario, Date fechaModificacion,
			String usuarioModificacion) {
		this.id = id;
		this.ordenesEntrada = ordenesEntrada;
		this.idProducto = idProducto;
		this.numeroLote = numeroLote;
		this.cantidad = cantidad;
		this.idUnidadMedida = idUnidadMedida;
		this.cantidadEstandar = cantidadEstandar;
		this.idUnidadMedidaEstandar = idUnidadMedidaEstandar;
		this.idEstadoInventario = idEstadoInventario;
		this.fechaModificacion = fechaModificacion;
		this.usuarioModificacion = usuarioModificacion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idOrdenEntrada", column = @Column(name = "Id_Orden_Entrada", nullable = false) ),
			@AttributeOverride(name = "numeroLinea", column = @Column(name = "Numero_Linea", nullable = false) ) })
	public LineasOrdenEntradaId getId() {
		return this.id;
	}

	public void setId(LineasOrdenEntradaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_Orden_Entrada", nullable = false, insertable = false, updatable = false)
	public OrdenesEntrada getOrdenesEntrada() {
		return this.ordenesEntrada;
	}

	public void setOrdenesEntrada(OrdenesEntrada ordenesEntrada) {
		this.ordenesEntrada = ordenesEntrada;
	}

	@Column(name = "Id_Producto", nullable = false)
	public String getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(String idProducto) {
		this.idProducto = idProducto;
	}

	@Column(name = "Numero_Lote")
	public String getNumeroLote() {
		return this.numeroLote;
	}

	public void setNumeroLote(String numeroLote) {
		this.numeroLote = numeroLote;
	}

	@Column(name = "Cantidad", nullable = false)
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "Id_Unidad_Medida", nullable = false)
	public String getIdUnidadMedida() {
		return this.idUnidadMedida;
	}

	public void setIdUnidadMedida(String idUnidadMedida) {
		this.idUnidadMedida = idUnidadMedida;
	}

	@Column(name = "Cantidad_Estandar", nullable = false)
	public Integer getCantidadEstandar() {
		return this.cantidadEstandar;
	}

	public void setCantidadEstandar(Integer cantidadEstandar) {
		this.cantidadEstandar = cantidadEstandar;
	}

	@Column(name = "Id_Unidad_Medida_Estandar", nullable = false)
	public String getIdUnidadMedidaEstandar() {
		return this.idUnidadMedidaEstandar;
	}

	public void setIdUnidadMedidaEstandar(String idUnidadMedidaEstandar) {
		this.idUnidadMedidaEstandar = idUnidadMedidaEstandar;
	}

	@Column(name = "Id_Estado_Inventario", nullable = false)
	public String getIdEstadoInventario() {
		return this.idEstadoInventario;
	}

	public void setIdEstadoInventario(String idEstadoInventario) {
		this.idEstadoInventario = idEstadoInventario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Modificacion", nullable = false, length = 23)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "Usuario_Modificacion", nullable = false, length = 50)
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

}
